import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import { BarChart3, Bell, Check, ChevronDown, ClipboardList, ExternalLink, Globe2, LayoutDashboard, LogOut, Pencil, Plus, QrCode, Search, Settings, ShoppingBag, Sparkles, Trash2, UtensilsCrossed, X } from 'lucide-react'
import { hasSupabaseConfig, supabase } from './lib/supabase'
import './App.css'

type MenuItem = { id: string | number; name: string; description: string; price: number; category: string; image: string; popular?: boolean }
type Order = { id: string | number; itemNames: string[]; total: number; status: 'New' | 'Preparing' | 'Ready' | 'Delivered' | 'Completed' | 'Cancelled'; createdAt: string; timestamp?: string }
type RestaurantSettings = { name: string; tagline: string; openUntil: string; languages: string[] }
type Deal = { name: string; description: string; price: number; oldPrice: number }
type RemoteRestaurant = { id: string; name: string; tagline: string; open_until: string; menu_slug: string }
type Category = { id: string | number; name: string }

const initialItems: MenuItem[] = [
  { id: 1, name: 'Burrata Pugliese', description: 'Creamy burrata, heirloom tomatoes, basil oil', price: 14, category: 'Antipasti', image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=900&q=85', popular: true },
  { id: 2, name: 'Tagliatelle al Tartufo', description: 'Fresh pasta, black truffle, parmigiano', price: 24, category: 'Pasta', image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85', popular: true },
  { id: 3, name: 'Branzino alla Griglia', description: 'Charred sea bass, lemon, salsa verde', price: 29, category: 'Secondi', image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=85' },
  { id: 4, name: 'Tiramisù della Casa', description: 'Mascarpone, espresso, cocoa, amaretti', price: 10, category: 'Dolci', image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=85' },
]
const defaultCategories: Category[] = [{ id: 'antipasti', name: 'Antipasti' }, { id: 'pasta', name: 'Pasta' }, { id: 'secondi', name: 'Secondi' }, { id: 'dolci', name: 'Dolci' }]
const translations: Record<string, Record<string, string>> = { English: { order: 'Add to order', deal: "Today's special", open: 'Open until' }, Español: { order: 'Añadir al pedido', deal: 'Especial de hoy', open: 'Abierto hasta' }, Deutsch: { order: 'Bestellen', deal: 'Tagesangebot', open: 'Geöffnet bis' }, Français: { order: 'Ajouter', deal: 'Suggestion du jour', open: "Ouvert jusqu'à" } }
const read = <T,>(key: string, fallback: T): T => { try { return JSON.parse(localStorage.getItem(key) || '') as T } catch { return fallback } }
const publicSlug = new URLSearchParams(window.location.search).get('restaurant')
const publicMenuUrl = (slug: string) => `${window.location.origin}/?restaurant=${encodeURIComponent(slug)}`

function App() {
  const [items, setItems] = useState<MenuItem[]>(() => hasSupabaseConfig ? [] : read('la-tavola-items', initialItems))
  const [orders, setOrders] = useState<Order[]>(() => hasSupabaseConfig ? [] : read('la-tavola-orders', []))
  const [settings, setSettings] = useState<RestaurantSettings>(() => read('la-tavola-settings', { name: 'La Tavola', tagline: 'Casa Italiana', openUntil: '23:00', languages: ['English', 'Español', 'Deutsch', 'Français'] }))
  const [deal, setDeal] = useState(() => read('la-tavola-deal', { name: 'Risotto ai Funghi', description: 'Wild mushrooms · pecorino · thyme', price: 18, oldPrice: 24 }))
  const [view, setView] = useState<'dashboard' | 'customer'>('dashboard')
  const [activeTab, setActiveTab] = useState('Overview')
  const [language, setLanguage] = useState('English')
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('All items')
  const [categories, setCategories] = useState<Category[]>(() => hasSupabaseConfig ? [] : read('la-tavola-categories', defaultCategories))
  const [cart, setCart] = useState<MenuItem[]>([])
  const [modal, setModal] = useState<'item' | 'qr' | 'auth' | 'deal' | 'cart' | 'category' | 'track' | null>('auth')
  const [editingItem, setEditingItem] = useState<MenuItem | null>(null)
  const [authMode, setAuthMode] = useState<'signin' | 'signup'>('signin')
  const [isSignedIn, setIsSignedIn] = useState(false)
  const [restaurant, setRestaurant] = useState<RemoteRestaurant | null>(null)
  const [backendError, setBackendError] = useState('')
  const [loadingBackend, setLoadingBackend] = useState(false)
  const [publicReady, setPublicReady] = useState(false)
  const copy = translations[language] || translations.English

  useEffect(() => localStorage.setItem('la-tavola-items', JSON.stringify(items)), [items])
  useEffect(() => localStorage.setItem('la-tavola-orders', JSON.stringify(orders)), [orders])
  useEffect(() => localStorage.setItem('la-tavola-settings', JSON.stringify(settings)), [settings])
  useEffect(() => localStorage.setItem('la-tavola-deal', JSON.stringify(deal)), [deal])
  useEffect(() => localStorage.setItem('la-tavola-categories', JSON.stringify(categories)), [categories])
  useEffect(() => {
    if (!supabase) return
    supabase.auth.getSession().then(({ data }) => { setIsSignedIn(Boolean(data.session)); if (data.session) setModal(null) })
    const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { setIsSignedIn(Boolean(session)); setModal(session ? null : 'auth') })
    return () => listener.subscription.unsubscribe()
  }, [])
  useEffect(() => {
    if (!isSignedIn || !supabase) return
    const client = supabase
    let mounted = true
    const loadBackendData = async () => {
      setLoadingBackend(true); setBackendError('')
      const restaurantResult = await client.from('restaurants').select('id,name,tagline,open_until,menu_slug').order('created_at', { ascending: true }).limit(1).maybeSingle()
      if (restaurantResult.error || !restaurantResult.data) { if (mounted) setBackendError(restaurantResult.error?.message || 'No restaurant is linked to this account yet.'); setLoadingBackend(false); return }
      const currentRestaurant = restaurantResult.data as RemoteRestaurant
      const [menuResult, dealResult, ordersResult, categoriesResult] = await Promise.all([
        client.from('menu_items').select('*').eq('restaurant_id', currentRestaurant.id).eq('is_published', true).order('created_at'),
        client.from('daily_deals').select('*').eq('restaurant_id', currentRestaurant.id).eq('active', true).maybeSingle(),
        client.from('orders').select('id,total,status,created_at,order_items(item_name,quantity)').eq('restaurant_id', currentRestaurant.id).order('created_at', { ascending: false }),
        client.from('categories').select('id,name').eq('restaurant_id', currentRestaurant.id).order('sort_order'),
      ])
      const categoriesUnavailable = categoriesResult.error?.code === 'PGRST205' || categoriesResult.error?.code === '42P01'
      if (menuResult.error || dealResult.error || ordersResult.error || (categoriesResult.error && !categoriesUnavailable)) { if (mounted) setBackendError(menuResult.error?.message || dealResult.error?.message || ordersResult.error?.message || categoriesResult.error?.message || 'Could not load restaurant data.'); setLoadingBackend(false); return }
      if (!mounted) return
      setRestaurant(currentRestaurant)
      setSettings({ name: currentRestaurant.name, tagline: currentRestaurant.tagline, openUntil: String(currentRestaurant.open_until).slice(0, 5), languages: ['English', 'Español', 'Deutsch', 'Français'] })
      setItems((menuResult.data || []).map((item) => ({ id: item.id, name: item.name, description: item.description, price: Number(item.price), category: item.category, image: item.image_url, popular: item.is_popular })))
      const loadedCategories = categoriesUnavailable ? defaultCategories : (categoriesResult.data || []).map((item) => ({ id: item.id, name: item.name }))
      localStorage.setItem('la-tavola-categories', JSON.stringify(loadedCategories))
      setCategories(loadedCategories)
      if (dealResult.data) setDeal({ name: dealResult.data.name, description: dealResult.data.description, price: Number(dealResult.data.price), oldPrice: Number(dealResult.data.old_price || dealResult.data.price) })
      setOrders((ordersResult.data || []).map((order) => ({ id: order.id, itemNames: (order.order_items || []).map((item: { item_name: string; quantity: number }) => `${item.item_name} x${item.quantity}`), total: Number(order.total), status: order.status, createdAt: new Date(order.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), timestamp: order.created_at })))
      setLoadingBackend(false)
    }
    void loadBackendData()
    return () => { mounted = false }
  }, [isSignedIn])
  useEffect(() => {
    if (!supabase || !restaurant || !isSignedIn) return
    const client = supabase
    const refreshOrders = async () => {
      const result = await client.from('orders').select('id,total,status,created_at,order_items(item_name,quantity)').eq('restaurant_id', restaurant.id).order('created_at', { ascending: false })
      if (!result.error) setOrders((result.data || []).map((order) => ({ id: order.id, itemNames: (order.order_items || []).map((item: { item_name: string; quantity: number }) => `${item.item_name} x${item.quantity}`), total: Number(order.total), status: order.status, createdAt: new Date(order.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), timestamp: order.created_at })))
    }
    const channel = client.channel(`restaurant-orders-${restaurant.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'orders', filter: `restaurant_id=eq.${restaurant.id}` }, () => { void refreshOrders() }).subscribe()
    return () => { void client.removeChannel(channel) }
  }, [restaurant, isSignedIn])
  useEffect(() => {
    if (!publicSlug || !supabase) return
    const client = supabase
    let mounted = true
    const loadPublicMenu = async () => {
      setLoadingBackend(true); setBackendError('')
      const restaurantResult = await client.rpc('get_public_restaurant', { restaurant_menu_slug: publicSlug })
      if (restaurantResult.error || !restaurantResult.data?.[0]) { if (mounted) setBackendError(restaurantResult.error?.message || 'This QR menu is not available.'); setLoadingBackend(false); return }
      const currentRestaurant = restaurantResult.data[0] as RemoteRestaurant
      const [menuResult, dealResult] = await Promise.all([
        client.from('menu_items').select('*').eq('restaurant_id', currentRestaurant.id).eq('is_published', true).order('created_at'),
        client.from('daily_deals').select('*').eq('restaurant_id', currentRestaurant.id).eq('active', true).maybeSingle(),
      ])
      if (menuResult.error || dealResult.error) { if (mounted) setBackendError(menuResult.error?.message || dealResult.error?.message || 'Could not load this menu.'); setLoadingBackend(false); return }
      if (!mounted) return
      setRestaurant(currentRestaurant); setSettings({ name: currentRestaurant.name, tagline: currentRestaurant.tagline, openUntil: String(currentRestaurant.open_until).slice(0, 5), languages: ['English', 'Español', 'Deutsch', 'Français'] })
      setItems((menuResult.data || []).map((item) => ({ id: item.id, name: item.name, description: item.description, price: Number(item.price), category: item.category, image: item.image_url, popular: item.is_popular })))
      if (dealResult.data) setDeal({ name: dealResult.data.name, description: dealResult.data.description, price: Number(dealResult.data.price), oldPrice: Number(dealResult.data.old_price || dealResult.data.price) })
      setPublicReady(true); setLoadingBackend(false)
    }
    void loadPublicMenu()
    return () => { mounted = false }
  }, [])

  const openItem = (item?: MenuItem) => { setEditingItem(item || null); setModal('item') }
  const createCategoryName = async (name: string) => { const cleanName = name.trim(); if (!cleanName || categories.some((categoryItem) => categoryItem.name.toLowerCase() === cleanName.toLowerCase())) return; if (supabase && restaurant) { const result = await supabase.from('categories').insert({ restaurant_id: restaurant.id, name: cleanName, sort_order: categories.length }).select('id,name').single(); if (result.error) { setBackendError(result.error.message); return } const nextCategories = [...categories, result.data]; localStorage.setItem('la-tavola-categories', JSON.stringify(nextCategories)); setCategories(nextCategories); } else { const nextCategories = [...categories, { id: Date.now(), name: cleanName }]; localStorage.setItem('la-tavola-categories', JSON.stringify(nextCategories)); setCategories(nextCategories) } setModal(null) }
  const addCategory = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await createCategoryName(String(new FormData(event.currentTarget).get('name'))) }
  useEffect(() => { const handler = (event: Event) => { const name = (event as CustomEvent<string>).detail; void createCategoryName(name) }; window.addEventListener('la-tavola-add-category', handler); return () => window.removeEventListener('la-tavola-add-category', handler) })
  const saveItem = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    let image = String(data.get('image'))
    const imageFile = data.get('imageFile')
    if (!image && !(imageFile instanceof File && imageFile.size > 0)) { setBackendError('Choose an image from your gallery or add an image URL.'); return }
    if (supabase && restaurant && imageFile instanceof File && imageFile.size > 0) {
      const extension = imageFile.name.split('.').pop()?.toLowerCase() || 'jpg'
      const path = `${restaurant.id}/${crypto.randomUUID()}.${extension}`
      const upload = await supabase.storage.from('restaurant-images').upload(path, imageFile, { upsert: true, contentType: imageFile.type })
      if (upload.error) { setBackendError(upload.error.message); return }
      image = supabase.storage.from('restaurant-images').getPublicUrl(path).data.publicUrl
    }
    const next: MenuItem = { id: editingItem?.id || Date.now(), name: String(data.get('name')), description: String(data.get('description')), price: Number(data.get('price')), category: String(data.get('category')), image, popular: data.get('popular') === 'on' }
    if (supabase && restaurant) {
      const payload = { restaurant_id: restaurant.id, name: next.name, description: next.description, price: next.price, category: next.category, image_url: next.image, is_popular: next.popular }
      const result = editingItem ? await supabase.from('menu_items').update(payload).eq('id', String(editingItem.id)).eq('restaurant_id', restaurant.id).select().single() : await supabase.from('menu_items').insert(payload).select().single()
      if (result.error) { setBackendError(result.error.message); return }
      const saved = result.data
      setItems((current) => editingItem ? current.map((item) => item.id === editingItem.id ? next : item) : [...current, { ...next, id: saved.id }])
      setModal(null)
      return
    }
    setItems((current) => editingItem ? current.map((item) => item.id === editingItem.id ? next : item) : [...current, next])
    setModal(null)
  }
  const deleteItem = async (id: string | number) => { if (supabase && restaurant) { const result = await supabase.from('menu_items').delete().eq('id', String(id)).eq('restaurant_id', restaurant.id); if (result.error) { setBackendError(result.error.message); return } } setItems((current) => current.filter((item) => item.id !== id)) }
  const addToCart = (item: MenuItem) => {
    setCart((current) => [...current, item])
    setModal('cart')
  }
  const changeCartQuantity = (itemId: string | number, delta: number) => {
    setCart((current) => {
      const index = current.findIndex((item) => String(item.id) === String(itemId))
      if (index < 0) return current
      if (delta > 0) return [...current, current[index]]
      const next = [...current]
      next.splice(index, 1)
      return next
    })
    setModal('cart')
  }
  const submitOrder = async () => { if (!cart.length) return; setBackendError(''); const grouped = Array.from(new Map(cart.map((item) => [String(item.id), item])).values()).map((item) => ({ item, quantity: cart.filter((cartItem) => String(cartItem.id) === String(item.id)).length })); const total = grouped.reduce((sum, entry) => sum + entry.item.price * entry.quantity, 0); if (supabase && restaurant) { const rpcItems = grouped.map(({ item, quantity }) => ({ menu_item_id: typeof item.id === 'string' ? item.id : null, item_name: item.name, unit_price: item.price, quantity })); const orderResult = await supabase.rpc('create_customer_order', { target_restaurant: restaurant.id, order_total: total, order_items: rpcItems }); let created = orderResult.data?.[0]; if (orderResult.error?.code === 'PGRST202') { const directId = crypto.randomUUID(); const directToken = crypto.randomUUID().replaceAll('-', ''); const directOrder = await supabase.from('orders').insert({ id: directId, restaurant_id: restaurant.id, tracking_token: directToken, total, status: 'New' }); if (directOrder.error) { setBackendError(directOrder.error.message); return } const directItems = await supabase.from('order_items').insert(rpcItems.map((item) => ({ ...item, order_id: directId }))); if (directItems.error) { setBackendError(directItems.error.message); return } created = { id: directId, total, status: 'New', created_at: new Date().toISOString() } } if (orderResult.error && orderResult.error.code !== 'PGRST202') { setBackendError(orderResult.error.message); return } if (!created) { setBackendError('Could not place this order.'); return } setOrders((current) => [{ id: created.id, itemNames: grouped.map(({ item, quantity }) => `${item.name} x${quantity}`), total, status: 'New', createdAt: new Date(created.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), timestamp: created.created_at }, ...current]); } else { const now = new Date().toISOString(); setOrders((current) => [{ id: Date.now(), itemNames: grouped.map(({ item, quantity }) => `${item.name} x${quantity}`), total, status: 'New', createdAt: new Date(now).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), timestamp: now }, ...current]) } setCart([]); setModal(null) }
  const filteredItems = items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()) && (category === 'All items' || item.category === category))
  const changeOrderStatus = async (id: string | number, status: Order['status']) => { if (supabase && restaurant) { const result = await supabase.from('orders').update({ status }).eq('id', String(id)).eq('restaurant_id', restaurant.id); if (result.error) { setBackendError(result.error.message); return } } setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)) }
  const saveDeal = async (next: Deal) => { if (supabase && restaurant) { const result = await supabase.from('daily_deals').upsert({ restaurant_id: restaurant.id, name: next.name, description: next.description, price: next.price, old_price: next.oldPrice, active: true }, { onConflict: 'restaurant_id' }); if (result.error) { setBackendError(result.error.message); return } } setDeal(next); setModal(null) }
  const authenticate = async (mode: 'signin' | 'signup', email: string, password: string, restaurantName: string) => {
    if (!supabase) throw new Error('Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local.')
    if (mode === 'signup') throw new Error('Account creation is restricted. Ask the owner for access.')
    if (mode === 'signin') {
      const { error } = await supabase.auth.signInWithPassword({ email, password })
      if (error) throw error
    } else {
      const { error } = await supabase.auth.signUp({ email, password, options: { data: { restaurant_name: restaurantName, full_name: email.split('@')[0] } } })
      if (error) throw error
      throw new Error('Account created. Check your email for the verification link before signing in.')
    }
  }
  const signOut = async () => { await supabase?.auth.signOut(); setIsSignedIn(false); setModal('auth') }

  if (publicSlug && (loadingBackend || !publicReady)) { if (backendError) return <div className="backend-state"><div className="brand-mark large">LT</div><h2>Menu unavailable</h2><p>{backendError}</p></div>; return <div className="backend-state"><div className="brand-mark large">LT</div><h2>Loading menu...</h2><p>Fetching the restaurant's latest menu.</p></div> }
  if (publicSlug && publicReady) return <><CustomerMenu settings={settings} deal={deal} items={items} language={language} setLanguage={setLanguage} copy={copy} cart={cart} addToCart={addToCart} changeQuantity={changeCartQuantity} onTrack={() => setModal('track')} onCart={() => setModal('cart')} onBack={() => window.history.back()} />{backendError && <div className="action-error-toast">{backendError}</div>}{modal === 'track' && <CustomerOrderStatus orders={orders} onClose={() => setModal(null)} />}{modal === 'cart' && <CartModal cart={cart} onChangeQuantity={changeCartQuantity} onClose={() => setModal(null)} onSubmit={submitOrder} />}</>
  if (!isSignedIn) return <AuthModal mode={authMode} setMode={setAuthMode} onAuthenticate={authenticate} onClose={() => undefined} configured={hasSupabaseConfig} />
  if (loadingBackend) return <div className="backend-state"><div className="brand-mark large">LT</div><h2>Loading your restaurant...</h2><p>Securely fetching your private menu and orders.</p></div>
  if (backendError) return <div className="backend-state"><div className="brand-mark large">LT</div><h2>Restaurant data unavailable</h2><p>{backendError}</p><button className="primary-button" onClick={() => window.location.reload()}>Retry</button></div>
  if (view === 'customer') return <><CustomerMenu settings={settings} deal={deal} items={items} language={language} setLanguage={setLanguage} copy={copy} cart={cart} addToCart={addToCart} changeQuantity={changeCartQuantity} onTrack={() => setModal('track')} onCart={() => setModal('cart')} onBack={() => setView('dashboard')} />{modal === 'track' && <CustomerOrderStatus orders={orders} onClose={() => setModal(null)} />}{modal === 'cart' && <CartModal cart={cart} onChangeQuantity={changeCartQuantity} onClose={() => setModal(null)} onSubmit={submitOrder} />}</>
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">LT</span><span>{settings.name}</span></div><div className="restaurant-switcher"><span className="restaurant-dot">L</span><span><b>{settings.name}</b><small>Owner account</small></span><ChevronDown size={15} /></div><nav className="side-nav">{[['Overview', LayoutDashboard], ['Menu', UtensilsCrossed], ['Orders', ClipboardList], ['Settings', Settings]].map(([label, Icon]) => <button key={label as string} className={activeTab === label ? 'active' : ''} onClick={() => setActiveTab(label as string)}><Icon size={18} />{label as string}{label === 'Orders' && <span className="nav-count">{orders.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><Sparkles size={18} /><b>Make your menu multilingual</b><span>Reach every guest at the table.</span><button onClick={() => setView('customer')}>Preview menu <ExternalLink size={13} /></button></div><button className="profile" onClick={() => { void signOut(); setAuthMode('signin') }}><span className="avatar">AS</span><span><b>Alessandro S.</b><small>Restaurant owner</small></span><LogOut size={16} /></button></div></aside>
    <main className="main-content"><header className="topbar"><div><p className="eyebrow">Tuesday, 24 September 2024</p><h1>{activeTab === 'Overview' ? 'Good morning, Alessandro' : activeTab} <span>✦</span></h1></div><div className="top-actions"><button className="icon-button" aria-label="Notifications"><Bell size={19} /><i /></button><button className="outline-button" onClick={() => setView('customer')}><ExternalLink size={16} /> View live menu</button><button className="primary-button" onClick={() => setModal('qr')}><QrCode size={17} /> Share QR</button></div></header>
      {activeTab === 'Orders' ? <OrdersPanel orders={orders} onStatus={changeOrderStatus} /> : activeTab === 'Settings' ? <SettingsPanel settings={settings} setSettings={setSettings} /> : <><section className="deal-banner"><div><span className="deal-kicker"><Sparkles size={14} /> LIVE DEAL</span><h2>Make today taste <em>exceptional.</em></h2><p>Set your daily special and make it the first thing guests see when they scan.</p></div><div className="deal-preview"><span>Today at {settings.name}</span><strong>{deal.name}</strong><small>{deal.description}</small><b>€{deal.price} <del>€{deal.oldPrice}</del></b></div><button className="deal-edit" onClick={() => setModal('deal')}>Edit deal <Settings size={15} /></button></section><div className="section-heading"><div><h2>{activeTab === 'Menu' ? 'Menu collection' : 'Your restaurant at a glance'}</h2><p>{activeTab === 'Menu' ? 'Keep your dishes fresh and ready to discover.' : 'Everything is looking delicious.'}</p></div><div className="updated"><span className="status-dot" />All changes saved</div></div>{activeTab === 'Overview' && <section className="stats-grid"><Stat icon={<UtensilsCrossed size={18} />} tone="green" label="MENU ITEMS" value={String(items.length)} note="Live on your QR menu" /><Stat icon={<ShoppingBag size={18} />} tone="orange" label="ORDERS TODAY" value={String(orders.length)} note="From your digital menu" /><Stat icon={<Globe2 size={18} />} tone="blue" label="MENU LANGUAGES" value={String(settings.languages.length)} note="Ready for your guests" /><div className="stat-card qr-stat"><span className="stat-icon red"><QrCode size={18} /></span><small>YOUR QR MENU</small><strong>Active</strong><button onClick={() => setModal('qr')}>Manage QR <ChevronDown size={14} /></button></div></section>}<MenuManager items={filteredItems} search={search} setSearch={setSearch} category={category} setCategory={setCategory} onAdd={() => openItem()} onEdit={openItem} onDelete={deleteItem} /></>}
    </main>
    {modal === 'cart' && <CartModal cart={cart} onChangeQuantity={changeCartQuantity} onClose={() => setModal(null)} onSubmit={submitOrder} />}
    {modal === 'item' && <ItemModal item={editingItem} categories={categories} onClose={() => setModal(null)} onSave={saveItem} />}{modal === 'category' && <CategoryModal onClose={() => setModal(null)} onSave={addCategory} />}{modal === 'deal' && <DealModal deal={deal} items={items} onClose={() => setModal(null)} onSave={saveDeal} />}{modal === 'qr' && <QrModal url={publicMenuUrl(restaurant?.menu_slug || 'la-tavola')} onClose={() => setModal(null)} />}{modal === 'auth' && !isSignedIn && <AuthModal mode={authMode} setMode={setAuthMode} onAuthenticate={authenticate} onClose={() => setModal(null)} />}
  </div>
}

function Stat({ icon, tone, label, value, note }: { icon: ReactNode; tone: string; label: string; value: string; note: string }) { return <div className="stat-card"><span className={`stat-icon ${tone}`}>{icon}</span><small>{label}</small><strong>{value}</strong><span className="stat-note">{note}</span></div> }
function MenuManager({ items, categories = read('la-tavola-categories', defaultCategories), search, setSearch, category, setCategory, onAdd, onAddCategory = () => { const name = window.prompt('Category name'); if (name) window.dispatchEvent(new CustomEvent('la-tavola-add-category', { detail: name })) }, onEdit, onDelete }: { items: MenuItem[]; categories?: Category[]; search: string; setSearch: (value: string) => void; category: string; setCategory: (value: string) => void; onAdd: () => void; onAddCategory?: () => void; onEdit: (item: MenuItem) => void; onDelete: (id: string | number) => void }) { const categoryNames = ['All items', ...Array.from(new Set([...categories.map((item) => item.name), ...items.map((item) => item.category)]))]; return <section className="menu-section"><div className="section-heading menu-heading"><div><h2>Menu collection</h2><p>{items.length} items currently published.</p></div><div className="heading-actions"><button className="outline-button" onClick={onAddCategory}><Plus size={15} /> Category</button><button className="primary-button" onClick={onAdd}><Plus size={17} /> Add item</button></div></div><div className="toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your menu" /></div><div className="filter-pills">{categoryNames.map((item) => <button key={item} className={category === item ? 'selected' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="item-grid">{items.map((item) => <article className="item-card" key={item.id}><div className="item-image"><img src={item.image} alt={item.name} />{item.popular && <span className="popular">Popular</span>}<button className="item-more" aria-label={`Edit ${item.name}`} onClick={() => onEdit(item)}><Pencil size={13} /></button></div><div className="item-info"><div><span className="category-label">{item.category}</span><h3>{item.name}</h3><p>{item.description}</p></div><div className="item-actions"><strong>€{item.price}</strong><button aria-label={`Delete ${item.name}`} onClick={() => onDelete(item.id)}><Trash2 size={13} /></button></div></div></article>)}</div></section> }
function OrdersPanel({ orders, onStatus }: { orders: Order[]; onStatus: (id: string | number, status: Order['status']) => void }) { const activeOrders = orders.filter((order) => order.status !== 'Delivered' && order.status !== 'Completed' && order.status !== 'Cancelled'); const deliveredOrders = orders.filter((order) => order.status === 'Delivered' || order.status === 'Completed'); return <><section className="data-panel"><div className="section-heading"><div><h2>Live orders</h2><p>Only orders that still need attention are shown here.</p></div><span className="status-dot" /></div>{activeOrders.length === 0 ? <div className="empty-state"><ClipboardList size={30} /><h3>All orders are delivered</h3><p>New orders will appear here automatically.</p></div> : <div className="orders-list">{activeOrders.map((order) => <article className="order-row" key={order.id}><div><b>Order #{String(order.id).slice(-4)}</b><small>{order.createdAt} · {order.itemNames.join(', ')}</small></div><strong>€{order.total}</strong><select value={order.status} onChange={(event) => onStatus(order.id, event.target.value as Order['status'])}><option>New</option><option>Preparing</option><option>Ready</option><option>Delivered</option></select></article>)}</div>}</section>{deliveredOrders.length > 0 && <section className="data-panel delivered-panel"><div className="section-heading"><div><h2>Delivered history</h2><p>Completed orders are archived here.</p></div><span className="status-dot" /></div><div className="orders-list">{deliveredOrders.map((order) => <article className="order-row delivered-row" key={order.id}><div><b>Order #{String(order.id).slice(-4)}</b><small>{order.createdAt} · {order.itemNames.join(', ')}</small></div><strong>€{order.total}</strong><span className="delivered-label">Delivered</span></article>)}</div></section>}<AnalyticsPanel orders={orders} /></> }
function AnalyticsPanel({ orders }: { orders: Order[] }) { const [range, setRange] = useState('Daily'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const now = new Date(); const start = new Date(now); if (range === 'Daily') start.setHours(0, 0, 0, 0); if (range === 'Weekly') start.setDate(now.getDate() - 7); if (range === 'Monthly') start.setMonth(now.getMonth() - 1); if (range === 'Yearly') start.setFullYear(now.getFullYear() - 1); const visible = orders.filter((order) => { const time = new Date(order.timestamp || 0).getTime(); if (range === 'Custom') { if (!from || !to) return true; return time >= new Date(`${from}T00:00:00`).getTime() && time <= new Date(`${to}T23:59:59`).getTime() } return time >= start.getTime() }); const revenue = visible.reduce((sum, order) => sum + order.total, 0); return <section className="data-panel analytics-panel"><div className="section-heading"><div><h2><BarChart3 size={20} /> Order tracking</h2><p>Review revenue and order volume across any period.</p></div><strong>€{revenue.toFixed(2)}</strong></div><div className="range-tabs">{['Daily', 'Weekly', 'Monthly', 'Yearly', 'Custom'].map((item) => <button className={range === item ? 'selected' : ''} key={item} onClick={() => setRange(item)}>{item}</button>)}</div>{range === 'Custom' && <div className="date-range"><label>From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></div>}<div className="analytics-stats"><div><small>ORDERS</small><b>{visible.length}</b></div><div><small>AVERAGE ORDER</small><b>€{visible.length ? (revenue / visible.length).toFixed(2) : '0.00'}</b></div><div><small>DELIVERED</small><b>{visible.filter((order) => order.status === 'Delivered').length}</b></div></div></section> }
function SettingsPanel({ settings, setSettings }: { settings: RestaurantSettings; setSettings: (settings: RestaurantSettings) => void }) { const [draft, setDraft] = useState(settings); return <section className="data-panel settings-panel"><div className="section-heading"><div><h2>Restaurant settings</h2><p>These details appear on your public QR menu.</p></div></div><label>Restaurant name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Tagline<input value={draft.tagline} onChange={(event) => setDraft({ ...draft, tagline: event.target.value })} /></label><label>Open until<input type="time" value={draft.openUntil} onChange={(event) => setDraft({ ...draft, openUntil: event.target.value })} /></label><button className="primary-button" onClick={() => setSettings(draft)}><Check size={16} /> Save settings</button></section> }
function ItemModal({ item, categories, onClose, onSave }: { item: MenuItem | null; categories: Category[]; onClose: () => void; onSave: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop" onClick={onClose}><form className="simple-modal" onClick={(event) => event.stopPropagation()} onSubmit={onSave}><button type="button" className="close-button" onClick={onClose}><X size={18} /></button><span className="modal-icon"><Plus /></span><h2>{item ? 'Edit menu item' : 'Add a menu item'}</h2><label>Dish name<input name="name" required defaultValue={item?.name || ''} placeholder="e.g. Pasta al Limone" /></label><label>Description<input name="description" required defaultValue={item?.description || ''} placeholder="Short description" /></label><label>Price<input name="price" required type="number" min="0" step="0.50" defaultValue={item?.price || 16} /></label><label>Category<select name="category" defaultValue={item?.category || categories[0]?.name}>{categories.map((categoryItem) => <option key={categoryItem.id}>{categoryItem.name}</option>)}</select></label><label>Image URL<input name="image" defaultValue={item?.image || ''} placeholder="Optional when choosing a gallery image" /></label><label>Or choose from gallery<input name="imageFile" type="file" accept="image/png,image/jpeg,image/webp" /></label><label className="check-label"><input name="popular" type="checkbox" defaultChecked={item?.popular} /> Mark as popular</label><button className="primary-button full" type="submit">{item ? 'Save changes' : 'Add to menu'} <Check size={16} /></button></form></div> }
function CategoryModal({ onClose, onSave }: { onClose: () => void; onSave: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop" onClick={onClose}><form className="simple-modal" onClick={(event) => event.stopPropagation()} onSubmit={onSave}><button type="button" className="close-button" onClick={onClose}><X size={18} /></button><span className="modal-icon"><Plus /></span><h2>Add a category</h2><p>Create a category for organizing your menu items.</p><label>Category name<input name="name" required placeholder="e.g. Pizza, Drinks" /></label><button className="primary-button full" type="submit">Create category <Check size={16} /></button></form></div> }
function DealModal({ deal, items, onClose, onSave }: { deal: Deal; items: MenuItem[]; onClose: () => void; onSave: (deal: Deal) => void }) { const selected = items.find((item) => item.name === deal.name) || items[0]; const [selectedId, setSelectedId] = useState(String(selected?.id || '')); const selectedItem = items.find((item) => String(item.id) === selectedId) || selected; const [price, setPrice] = useState(deal.price); return <div className="modal-backdrop" onClick={onClose}><div className="simple-modal" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button><span className="modal-icon"><Sparkles /></span><h2>Edit daily deal</h2><label>Choose from your menu<select value={selectedId} onChange={(event) => { setSelectedId(event.target.value); const item = items.find((candidate) => String(candidate.id) === event.target.value); if (item) setPrice(item.price) }}>{items.map((item) => <option key={item.id} value={String(item.id)}>{item.name} · €{item.price}</option>)}</select></label><label>Deal price<input type="number" min="0" value={price} onChange={(event) => setPrice(Number(event.target.value))} /></label><p>Only dishes already published in your menu can be used as a deal.</p><button className="primary-button full" disabled={!selectedItem} onClick={() => selectedItem && onSave({ name: selectedItem.name, description: selectedItem.description, price, oldPrice: selectedItem.price })}>Publish deal <Check size={16} /></button></div></div> }
function QrModal({ url, onClose }: { url: string; onClose: () => void }) { return <div className="modal-backdrop" onClick={onClose}><div className="qr-modal" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button><span className="modal-icon"><QrCode /></span><h2>Your menu, one scan away.</h2><p>Guests can scan this QR code to open your live menu.</p><div className="qr-wrap"><QRCodeSVG value={url} size={190} bgColor="#fffdf8" fgColor="#183b34" /></div><b className="qr-url">{url}</b><button className="primary-button full" onClick={() => navigator.clipboard?.writeText(url)}><ClipboardList size={16} /> Copy menu link</button></div></div> }
function AuthModal({ mode, setMode, onAuthenticate, onClose: _onClose, configured = true }: { mode: 'signin' | 'signup'; setMode: (mode: 'signin' | 'signup') => void; onAuthenticate: (mode: 'signin' | 'signup', email: string, password: string, restaurantName: string) => Promise<void>; onClose: () => void; configured?: boolean }) { const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); setBusy(true); const data = new FormData(event.currentTarget); try { await onAuthenticate(mode, String(data.get('email')), String(data.get('password')), String(data.get('restaurantName') || 'La Tavola')) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Authentication failed.') } finally { setBusy(false) } }; return <div className="modal-backdrop"><form className="simple-modal auth-modal" onSubmit={submit}><span className="brand-mark large">LT</span><h2>{mode === 'signin' ? 'Welcome back.' : 'Create your account.'}</h2><p>{mode === 'signin' ? 'Sign in to keep your restaurant menu in sync.' : 'Create a verified owner account for your restaurant.'}</p>{!configured && <div className="auth-error">Backend is not configured yet. Add your Supabase values to .env.local before using sign in.</div>}{error && <div className="auth-error">{error}</div>}{mode === 'signup' && <label>Restaurant name<input name="restaurantName" required placeholder="La Tavola" /></label>}<label>Email address<input name="email" required type="email" placeholder="you@restaurant.com" /></label><label>Password<input name="password" required minLength={6} type="password" placeholder="At least 6 characters" /></label><button className="primary-button full" type="submit" disabled={busy || !configured}>{busy ? 'Please wait...' : mode === 'signin' ? 'Sign in' : 'Create account'} <ExternalLink size={16} /></button><button type="button" className="text-button" onClick={() => { setError(''); setMode(mode === 'signin' ? 'signup' : 'signin') }}>{mode === 'signin' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button><small>Your email must be verified before your account can sign in.</small></form></div> }
function CartModal({ cart, onChangeQuantity, onClose, onSubmit }: { cart: MenuItem[]; onChangeQuantity: (itemId: string | number, delta: number) => void; onClose: () => void; onSubmit: () => void }) { const grouped = Array.from(new Map(cart.map((item) => [String(item.id), item])).values()).map((item) => ({ item, quantity: cart.filter((cartItem) => String(cartItem.id) === String(item.id)).length })); const total = grouped.reduce((sum, entry) => sum + entry.item.price * entry.quantity, 0); return <div className="modal-backdrop" onClick={onClose}><div className="simple-modal" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button><span className="modal-icon"><ShoppingBag /></span><h2>Your order</h2>{cart.length ? <><div className="cart-list">{grouped.map(({ item, quantity }) => <div className="cart-line" key={item.id}><span>{item.name}<small className="quantity-note">€{item.price} each</small></span><span className="quantity-control"><button onClick={() => onChangeQuantity(item.id, -1)}>-</button><b>{quantity}</b><button onClick={() => onChangeQuantity(item.id, 1)}>+</button></span></div>)}</div><div className="cart-total"><span>Total</span><strong>€{total}</strong></div><button className="primary-button full" onClick={onSubmit}>Place order <Check size={16} /></button></> : <div className="empty-state"><p>Your order is empty.</p><button className="outline-button" onClick={onClose}>Browse menu</button></div>}</div></div> }
function CustomerOrderStatus({ orders, onClose }: { orders: Order[]; onClose: () => void }) { const order = orders[0]; return <div className="modal-backdrop" onClick={onClose}><aside className="order-status-banner tracking-panel" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose}><X size={18} /></button>{order ? <><div className="order-status-head"><span><ClipboardList size={15} /> Order #{String(order.id).slice(-4)}</span><b>{order.status}</b></div><div className="order-progress">{['Received', 'Preparing', 'Ready'].map((step, index) => <span className={index < (order.status === 'New' ? 1 : order.status === 'Preparing' ? 2 : 3) ? 'done' : ''} key={step}><i />{step}</span>)}</div><small>{order.status === 'Delivered' ? 'Order delivered. Buon appetito!' : order.status === 'Ready' ? 'Your order is ready. Buon appetito!' : 'We are preparing your order with care.'}</small></> : <div className="empty-state"><h3>No active order</h3><p>Your placed order status will appear here.</p></div>}</aside></div> }
function CustomerMenu({ settings, deal, items, language, setLanguage, copy, cart, addToCart, changeQuantity, onTrack, onCart, onBack }: { settings: RestaurantSettings; deal: { name: string; description: string; price: number; oldPrice: number }; items: MenuItem[]; language: string; setLanguage: (language: string) => void; copy: Record<string, string>; cart: MenuItem[]; addToCart: (item: MenuItem) => void; changeQuantity: (itemId: string | number, delta: number) => void; onTrack: () => void; onCart: () => void; onBack: () => void }) { const quantityFor = (id: string | number) => cart.filter((item) => String(item.id) === String(id)).length; return <main className="customer-page"><header className="customer-top"><button className="customer-brand" onClick={onBack}><span className="brand-mark">LT</span><span>{settings.name}<small>{settings.tagline}</small></span></button><div className="customer-tools"><button className="outline-button track-button" onClick={onTrack}><ClipboardList size={15} /> Track order</button><label className="language-select"><Globe2 size={17} /><select value={language} onChange={(event) => setLanguage(event.target.value)}>{settings.languages.map((item) => <option key={item}>{item}</option>)}</select><ChevronDown size={14} /></label><button className="order-button" onClick={onCart}><ShoppingBag size={17} /> Order <span>{cart.length}</span></button></div></header><div className="customer-hero"><div><span className="live-badge"><i /> {copy.open} {settings.openUntil}</span><h1>Benvenuti<br /><em>at {settings.name}.</em></h1><p>Simple ingredients. Honest cooking. A table worth gathering around.</p></div></div><section className="customer-deal"><div><span>{copy.deal}</span><h2>{deal.name}</h2><p>{deal.description}</p></div><strong>€{deal.price} <del>€{deal.oldPrice}</del></strong></section><div className="customer-content"><div className="customer-intro"><div><span className="eyebrow">OUR MENU</span><h2>A little bit of Italy.</h2></div><p>Take your time. Every dish is made to order.</p></div><div className="customer-grid">{items.map((item) => <article className="customer-item" key={item.id}><img src={item.image} alt={item.name} /><div><span>{item.category}</span><h3>{item.name}</h3><p>{item.description}</p><footer><b>€{item.price}</b>{quantityFor(item.id) ? <span className="menu-quantity"><button onClick={() => changeQuantity(item.id, -1)}>-</button><strong>{quantityFor(item.id)}</strong><button onClick={() => changeQuantity(item.id, 1)}>+</button></span> : <button onClick={() => addToCart(item)}><Plus size={15} /> {copy.order}</button>}</footer></div></article>)}</div></div><footer className="customer-footer"><span>{settings.name}</span><span>Buon appetito · Made with care in Roma</span></footer></main> }

export default App
